version: '3'

services:
  terrad:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terra-node
    environment: 
      - MONIKER=NodeName
      # - GENESIS_URL= comment out for default 13003 (give url for cosmoshub-1)
    ports:
      - "26656:26656"
      - "26657:26657"
      - "26658:26658"
      - "1317:1317"
    # volumes:
    #   - ./data/config:/.terrad/config
    #   - ./data/keys:/.terracli/keys
