version: "3.4"
services:
  terra-money:
    build:
      args:
        UPSTREAM_VERSION: master
      context: ./build
      dockerfile: Dockerfile
    environment:
      - MONIKER=DAPPNodler
      - LOG_LEVEL=debug
      - CHAIN_ID=columbus-4
      - BOOTSTRAP="TRUE"
      - TERRAD_HOME=/.terrad
      - >-
        GENESIS_URL=https://columbus-genesis.s3-ap-northeast-1.amazonaws.com/columbus-4-genesis.json
      - ADDR_BOOK_STRICT="false"
      - PROMETHEUS_LISTEN_ADDR=56660
      - PROMETHEUS="true"
      - MAX_OPEN_CONNECTIONS=3
      - LCD_PORT=5317
      - RPC_PORT=56657
      - P2P_PORT=56656
      - PROXY_APP_PORT=56658
      - CORS_ALLOWED_ORIGINS=*
    restart: always
    ports:
      - "56656:56656"
      - "56657:56657"
      - "56658:56658"
      - "5317:5317"
    volumes:
      - "chain_data:/.terrad"
    image: "terra-money.public.dappnode.eth:0.1.0"
volumes:
  chain_data: {}
